### ISSUE TITLE
How can I add a multimedia slide here?

### ISSUE THREAD

**Issue by IvanJobs** [webpro/reveal-md#101]
Hi everyone,
I want to use reveal.js to make new kind of slides with more user interactions, for example user input, dragging, click and so on, how can I do that? as I know, reveal is just about text/picture, and normal animations, without user interaction.

**Comment by Sigmun** [comment]
I'm not sure but I think this is not a problem since you can write it in HTLM5/JS/PHP. Just include your html code as explained [here](https://github.com/webpro/reveal-md#custom-slide-attributes).
If it is not sufficient, you will need to go directly for writing your slides with [reveal.js](http://lab.hakim.se/reveal-js/)

**Comment by webpro** [comment]
You could also include your own [custom scripts](https://github.com/webpro/reveal-md#custom-scripts). I'm going to close this issue, since I believe this is a bit out of scope for reveal-js/md. Feel free to re-open if you'd like to discuss things further.
