### ISSUE TITLE
Template is not respected from CLI if in subdirectory

### ISSUE THREAD

**Issue by chbndrhnns** [webpro/reveal-md#311]
I cannot get my custom template to be used by reveal-md if I put it in `template/reveal.html`. 

Following the steps below should not render anything but instead, it shows the default reveal template.

## Steps 

1. Create `template/reveal.html`

```html
<html>

<head>
  <title>custom-template</title>
</head>

</html>
```

2. Create presentation `dummy.md`

```markdown
dummy.md


```

2. Run `reveal-md`

`reveal-md dummy.md --template template/reveal.html`

**Comment by chbndrhnns** [comment]
I do not se a change here and the issue persists.

**Comment by davidovich** [comment]
I have experienced this also, and I had not time to make a PR, but I believe it is related to how the [algorithm uses the default to trigger cwd consulting](https://github.com/webpro/reveal-md/blob/6947d73/lib/config.js#L86-L87). If you provide a path that is the same as the default ([`template/reveal.html`](https://github.com/webpro/reveal-md/blob/6947d73ab54b92b5f386f67d951065da01a9fea0/lib/defaults.json#L13)), it will short-circuit the cwd() prepend. This is fine with shipped templates, but breaks when a path is provided.

What would fix this is that if a user provides a path, just use that, otherwise give the default.

This also happens when using the dockerized version of reveal-md.

A workaround is to name your template with different name than the default.

**Comment by chbndrhnns** [comment]
I do not see a change here and the issue persists.

**Comment by webpro** [comment]
@chbndrhnns Why don't/can't you use a different path than "template/reveal.html"? Doesn't this work-around solve your issue?

**Comment by chbndrhnns** [comment]
@webpro The posted work-around helps me to work around the issue. This does not make the issue go away, though, which I would call a bug.

**Comment by webpro** [comment]
It's definitely a bug, but quite minor tbh. That's why I'm going to close this issue. If you or someone else feels the need to fix it, that would be great.
