### ISSUE TITLE
How do I add custom themes?

### ISSUE THREAD

**Issue by pburkholder** [webpro/reveal-md#36]
How do I add custom themes when using reveal-md? Not sure how to connect what's here with what's in https://github.com/hakimel/reveal.js/blob/master/css/theme/README.md

Any pointers are recommended.   Thanks, Peter

**Comment by webpro** [comment]
This seems to contain the information you're looking for: https://github.com/webpro/reveal-md/search?utf8=%E2%9C%93&q=theme, i.e. "theme" is an option you can use and it should match with one of the available reveal.js theme stylesheets.

**Comment by pburkholder** [comment]
Thanks. That was enough of a hint that I could place them (in OsX) `/usr/local/lib/node_modules/reveal-md/node_modules/reveal.js/css`

**Comment by jossemarGT** [comment]
Hi! Just in case someone else stumbles with the same scenario. Since `reveal-md#0.0.19` you can add a custom theme directory, like this `<slides directory>/theme/datheme.css` and then pass the `-t datheme` argument to the cli.

@webpro do you mind if make a PR just to add this to the `README.md` file?

**Comment by webpro** [comment]
@jossemarGT please do! Thanks in advance.

**Comment by jossemarGT** [comment]
@webpro there you are #48
