### ISSUE TITLE
Code-fragments or stretch no longer works

### ISSUE THREAD

**Issue by htl-scre** [webpro/reveal-md#380]
´´´
blocks
´´´
!-- .element: class="stretch fragment" --

no longer work, ignoring both classes in the resultung html
update: html cleared up

**Comment by webpro** [comment]
You're not providing any details. What exactly are you trying that does not work? No longer... what compared to what? Is the issue in reveal-md or reveal.js?

**Comment by htl-scre** [comment]
sorry, i think its a reveal-md problem, since the resulting html doesnt feature the classes
it did work in prior version of reveal-md

**Comment by bukowskiadam** [comment]
I just stumbled upon this, because I have the same problem. I had slides with code fragments which I wanted to fade in. It was something like:

![image](https://user-images.githubusercontent.com/1633333/127647398-ce64ac0f-532b-44e9-82ad-782f33a6a71e.png)

<details><summary>text content of the screenshot (remove backslashes)</summary>

```md
---

\```shell
$ git init
Initialized empty Git repository
\```
<!-- .element: class="fragment fade-in-then-semi-out" -->

\```shell
$ ls -l .git
total 24
...
\```
<!-- .element: class="fragment fade-in-then-semi-out" -->

\```shell
$ find .git/objects -type f
$
\```
<!-- .element: class="fragment fade-in-then-semi-out" -->

Notes:

speaker notes

---
```

</details>

and it did work in some older version of reveal-md. Today I've updated it from `3.0.4` to `5.1.2` and it does not work.

Previously generated html was like:
![image](https://user-images.githubusercontent.com/1633333/127647665-d8c5eaff-72da-4569-9238-da2b4f471ef2.png)

Now it's:
![image](https://user-images.githubusercontent.com/1633333/127647746-7bd7b923-0caa-420e-8307-9ce1c2bdb8ff.png)

So definitely it's missing additional css classes.

**Comment by bukowskiadam** [comment]
Turns out that this is a bug (imho) introduced by `reveal.js` here: https://github.com/hakimel/reveal.js/commit/c2fd760f8f14482510b3a3125dbb5f669579d477#diff-5593802c069698c07e23dedc8d2af07bcf26cccae5b5fa32316a61ff5bc8ec0bR38

**Comment by webpro** [comment]
Right, reveal-md contains the latest version of reveal.js (v4.1.3). However, the latest tag on GitHub is currently 4.1.2 (https://github.com/hakimel/reveal.js/releases) and the npm registry has 4.1.3 (https://www.npmjs.com/package/reveal.js).
